// Mock actor data for testing the actor database

import type { CreateActorInput } from '@/types';

export const mockActors: CreateActorInput[] = [
    {
        name: "Emma Thompson",
        age: 28,
        gender: "Female",
        race: "Caucasian",
        height: "5'6\"",
        representation: "SAG-AFTRA",
        tags: ["Drama", "Comedy", "Theater"],
        notes: "Experienced stage actor with strong dramatic range. Available for lead roles.",
        headshotUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Marcus Johnson",
        age: 35,
        gender: "Male",
        race: "African American",
        height: "6'1\"",
        representation: "AEA",
        tags: ["Action", "Drama", "Martial Arts"],
        notes: "Former stunt performer turned actor. Excellent physical presence.",
        headshotUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Sofia Rodriguez",
        age: 24,
        gender: "Female",
        race: "Hispanic/Latino",
        height: "5'4\"",
        representation: "Non-Union",
        tags: ["Comedy", "Musical", "Bilingual"],
        notes: "Fluent in Spanish and English. Strong singing voice and comedic timing.",
        headshotUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "David Chen",
        age: 42,
        gender: "Male",
        race: "Asian",
        height: "5'9\"",
        representation: "SAG-AFTRA",
        tags: ["Drama", "Character Actor", "Voice Over"],
        notes: "Veteran character actor with extensive TV and film credits.",
        headshotUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Isabella Martinez",
        age: 31,
        gender: "Female",
        race: "Hispanic/Latino",
        height: "5'7\"",
        representation: "SAG-AFTRA",
        tags: ["Drama", "Independent Film", "Method Acting"],
        notes: "Award-winning indie film actress. Specializes in complex dramatic roles.",
        headshotUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "James Wilson",
        age: 29,
        gender: "Male",
        race: "Caucasian",
        height: "5'11\"",
        representation: "AEA",
        tags: ["Comedy", "Improv", "Stand-up"],
        notes: "Professional comedian and improv performer. Great with ad-libbing.",
        headshotUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Aisha Patel",
        age: 26,
        gender: "Female",
        race: "South Asian",
        height: "5'5\"",
        representation: "Non-Union",
        tags: ["Drama", "Dance", "Classical Training"],
        notes: "Classically trained actress with dance background. Strong in period pieces.",
        headshotUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Robert Taylor",
        age: 48,
        gender: "Male",
        race: "Caucasian",
        height: "6'0\"",
        representation: "SAG-AFTRA",
        tags: ["Drama", "Authority Figures", "Corporate"],
        notes: "Experienced in playing executives, lawyers, and authority figures.",
        headshotUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Maya Thompson",
        age: 22,
        gender: "Female",
        race: "Mixed Race",
        height: "5'8\"",
        representation: "Non-Union",
        tags: ["Young Adult", "Social Media", "Commercial"],
        notes: "Rising talent with strong social media presence. Great for millennial roles.",
        headshotUrl: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Carlos Mendoza",
        age: 38,
        gender: "Male",
        race: "Hispanic/Latino",
        height: "5'10\"",
        representation: "SAG-AFTRA",
        tags: ["Action", "Thriller", "Bilingual"],
        notes: "Action specialist with military background. Fluent in Spanish.",
        headshotUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Rachel Kim",
        age: 33,
        gender: "Female",
        race: "Asian",
        height: "5'3\"",
        representation: "AEA",
        tags: ["Drama", "Independent Film", "Writer"],
        notes: "Actor-writer with several produced screenplays. Strong dramatic presence.",
        headshotUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face",
    },
    {
        name: "Tyler Brooks",
        age: 27,
        gender: "Male",
        race: "Caucasian",
        height: "6'2\"",
        representation: "Non-Union",
        tags: ["Sports", "Comedy", "Commercial"],
        notes: "Former college athlete. Great for sports-related roles and commercials.",
        headshotUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face",
    }
];

// Function to populate the store with mock data
export const loadMockActors = (addActor: (input: CreateActorInput) => void) => {
    mockActors.forEach(actor => {
        addActor(actor);
    });
};